### Home
GET http://localhost:3000/

### Get game data
GET http://localhost:3000/api/gamedata

### Get europe data
GET http://localhost:3000/api/europe

### Get post game data
POST http://localhost:3000/api/gamedata

